spring:
  datasource:
    url: jdbc:postgresql://172.17.0.2:5432/postgres
    username: postgres
    password: root

  main:
    allow-bean-definition-overriding: true

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
          non_contextual_creation: true
        ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect

